all:
	g++ -c observable.cpp
	g++ -c observer.cpp
	g++ -c presseagentur.cpp
	g++ -c fussballverein.cpp
	g++ -c main.cpp  
	g++ main.o fussballverein.o observable.o observer.o presseagentur.o -omain.exe

run:
	./main.exe

clean:
	rm *.o
	rm *.exe
	
	
