/* soapCalculatorPortBindingService.cpp
   Generated by gSOAP 2.8.16 from soap/calc.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapCalculatorPortBindingService.h"

CalculatorPortBindingService::CalculatorPortBindingService()
{	CalculatorPortBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

CalculatorPortBindingService::CalculatorPortBindingService(const struct soap &_soap) : soap(_soap)
{ }

CalculatorPortBindingService::CalculatorPortBindingService(soap_mode iomode)
{	CalculatorPortBindingService_init(iomode, iomode);
}

CalculatorPortBindingService::CalculatorPortBindingService(soap_mode imode, soap_mode omode)
{	CalculatorPortBindingService_init(imode, omode);
}

CalculatorPortBindingService::~CalculatorPortBindingService()
{ }

void CalculatorPortBindingService::CalculatorPortBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://webservice/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void CalculatorPortBindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void CalculatorPortBindingService::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	CalculatorPortBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
CalculatorPortBindingService *CalculatorPortBindingService::copy()
{	CalculatorPortBindingService *dup = SOAP_NEW_COPY(CalculatorPortBindingService(*(struct soap*)this));
	return dup;
}
#endif

int CalculatorPortBindingService::soap_close_socket()
{	return soap_closesock(this);
}

int CalculatorPortBindingService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int CalculatorPortBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int CalculatorPortBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int CalculatorPortBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int CalculatorPortBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void CalculatorPortBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void CalculatorPortBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *CalculatorPortBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void CalculatorPortBindingService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *CalculatorPortBindingService::soap_header()
{	return this->header;
}

int CalculatorPortBindingService::run(int port)
{	if (soap_valid_socket(this->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->error;
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET CalculatorPortBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET CalculatorPortBindingService::accept()
{	return soap_accept(this);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int CalculatorPortBindingService::ssl_accept()
{	return soap_ssl_accept(this);
}
#endif

int CalculatorPortBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns1__mul(CalculatorPortBindingService*);
static int serve_ns1__dic(CalculatorPortBindingService*);
static int serve_ns1__add(CalculatorPortBindingService*);
static int serve_ns1__min(CalculatorPortBindingService*);

int CalculatorPortBindingService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:mul"))
		return serve_ns1__mul(this);
	if (!soap_match_tag(this, this->tag, "ns1:dic"))
		return serve_ns1__dic(this);
	if (!soap_match_tag(this, this->tag, "ns1:add"))
		return serve_ns1__add(this);
	if (!soap_match_tag(this, this->tag, "ns1:min"))
		return serve_ns1__min(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns1__mul(CalculatorPortBindingService *soap)
{	struct ns1__mul soap_tmp_ns1__mul;
	struct ns1__mulResponse _param_1;
	soap_default_ns1__mulResponse(soap, &_param_1);
	soap_default_ns1__mul(soap, &soap_tmp_ns1__mul);
	if (!soap_get_ns1__mul(soap, &soap_tmp_ns1__mul, "ns1:mul", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->mul(soap_tmp_ns1__mul._arg0, soap_tmp_ns1__mul._arg1, _param_1);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__mulResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__mulResponse(soap, &_param_1, "ns1:mulResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__mulResponse(soap, &_param_1, "ns1:mulResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__dic(CalculatorPortBindingService *soap)
{	struct ns1__dic soap_tmp_ns1__dic;
	struct ns1__dicResponse _param_2;
	soap_default_ns1__dicResponse(soap, &_param_2);
	soap_default_ns1__dic(soap, &soap_tmp_ns1__dic);
	if (!soap_get_ns1__dic(soap, &soap_tmp_ns1__dic, "ns1:dic", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->dic(soap_tmp_ns1__dic._arg0, soap_tmp_ns1__dic._arg1, _param_2);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__dicResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__dicResponse(soap, &_param_2, "ns1:dicResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__dicResponse(soap, &_param_2, "ns1:dicResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__add(CalculatorPortBindingService *soap)
{	struct ns1__add soap_tmp_ns1__add;
	struct ns1__addResponse _param_3;
	soap_default_ns1__addResponse(soap, &_param_3);
	soap_default_ns1__add(soap, &soap_tmp_ns1__add);
	if (!soap_get_ns1__add(soap, &soap_tmp_ns1__add, "ns1:add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->add(soap_tmp_ns1__add._arg0, soap_tmp_ns1__add._arg1, _param_3);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__addResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__addResponse(soap, &_param_3, "ns1:addResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__addResponse(soap, &_param_3, "ns1:addResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__min(CalculatorPortBindingService *soap)
{	struct ns1__min soap_tmp_ns1__min;
	struct ns1__minResponse _param_4;
	soap_default_ns1__minResponse(soap, &_param_4);
	soap_default_ns1__min(soap, &soap_tmp_ns1__min);
	if (!soap_get_ns1__min(soap, &soap_tmp_ns1__min, "ns1:min", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->min(soap_tmp_ns1__min._arg0, soap_tmp_ns1__min._arg1, _param_4);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__minResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__minResponse(soap, &_param_4, "ns1:minResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__minResponse(soap, &_param_4, "ns1:minResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
