/* soapH.h
   Generated by gSOAP 2.8.16 from soap/calc.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_LONG64(soap, data),0) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__min
#define SOAP_TYPE_ns1__min (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__min(struct soap*, struct ns1__min *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__min(struct soap*, const struct ns1__min *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__min(struct soap*, const char*, int, const struct ns1__min *, const char*);
SOAP_FMAC3 struct ns1__min * SOAP_FMAC4 soap_in_ns1__min(struct soap*, const char*, struct ns1__min *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__min(struct soap*, const struct ns1__min *, const char*, const char*);

#ifndef soap_write_ns1__min
#define soap_write_ns1__min(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__min(soap, data),0) || soap_put_ns1__min(soap, data, "ns1:min", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__min * SOAP_FMAC4 soap_get_ns1__min(struct soap*, struct ns1__min *, const char*, const char*);

#ifndef soap_read_ns1__min
#define soap_read_ns1__min(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__min(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__min * SOAP_FMAC2 soap_instantiate_ns1__min(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__min * soap_new_ns1__min(struct soap *soap, int n = -1) { return soap_instantiate_ns1__min(soap, n, NULL, NULL, NULL); }

inline struct ns1__min * soap_new_req_ns1__min(struct soap *soap, int _arg0, int _arg1) { struct ns1__min *_p = soap_instantiate_ns1__min(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__min(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline struct ns1__min * soap_new_set_ns1__min(struct soap *soap, int _arg0, int _arg1) { struct ns1__min *_p = soap_instantiate_ns1__min(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__min(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline void soap_delete_ns1__min(struct soap *soap, struct ns1__min *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__min(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__minResponse
#define SOAP_TYPE_ns1__minResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__minResponse(struct soap*, struct ns1__minResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__minResponse(struct soap*, const struct ns1__minResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__minResponse(struct soap*, const char*, int, const struct ns1__minResponse *, const char*);
SOAP_FMAC3 struct ns1__minResponse * SOAP_FMAC4 soap_in_ns1__minResponse(struct soap*, const char*, struct ns1__minResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__minResponse(struct soap*, const struct ns1__minResponse *, const char*, const char*);

#ifndef soap_write_ns1__minResponse
#define soap_write_ns1__minResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__minResponse(soap, data),0) || soap_put_ns1__minResponse(soap, data, "ns1:minResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__minResponse * SOAP_FMAC4 soap_get_ns1__minResponse(struct soap*, struct ns1__minResponse *, const char*, const char*);

#ifndef soap_read_ns1__minResponse
#define soap_read_ns1__minResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__minResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__minResponse * SOAP_FMAC2 soap_instantiate_ns1__minResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__minResponse * soap_new_ns1__minResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__minResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__minResponse * soap_new_req_ns1__minResponse(struct soap *soap, LONG64 _return_) { struct ns1__minResponse *_p = soap_instantiate_ns1__minResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__minResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ns1__minResponse * soap_new_set_ns1__minResponse(struct soap *soap, LONG64 _return_) { struct ns1__minResponse *_p = soap_instantiate_ns1__minResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__minResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ns1__minResponse(struct soap *soap, struct ns1__minResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__minResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__add
#define SOAP_TYPE_ns1__add (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__add(struct soap*, struct ns1__add *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__add(struct soap*, const struct ns1__add *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__add(struct soap*, const char*, int, const struct ns1__add *, const char*);
SOAP_FMAC3 struct ns1__add * SOAP_FMAC4 soap_in_ns1__add(struct soap*, const char*, struct ns1__add *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__add(struct soap*, const struct ns1__add *, const char*, const char*);

#ifndef soap_write_ns1__add
#define soap_write_ns1__add(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__add(soap, data),0) || soap_put_ns1__add(soap, data, "ns1:add", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__add * SOAP_FMAC4 soap_get_ns1__add(struct soap*, struct ns1__add *, const char*, const char*);

#ifndef soap_read_ns1__add
#define soap_read_ns1__add(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__add(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__add * SOAP_FMAC2 soap_instantiate_ns1__add(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__add * soap_new_ns1__add(struct soap *soap, int n = -1) { return soap_instantiate_ns1__add(soap, n, NULL, NULL, NULL); }

inline struct ns1__add * soap_new_req_ns1__add(struct soap *soap, int _arg0, int _arg1) { struct ns1__add *_p = soap_instantiate_ns1__add(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__add(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline struct ns1__add * soap_new_set_ns1__add(struct soap *soap, int _arg0, int _arg1) { struct ns1__add *_p = soap_instantiate_ns1__add(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__add(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline void soap_delete_ns1__add(struct soap *soap, struct ns1__add *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__add(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__addResponse
#define SOAP_TYPE_ns1__addResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__addResponse(struct soap*, struct ns1__addResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__addResponse(struct soap*, const struct ns1__addResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__addResponse(struct soap*, const char*, int, const struct ns1__addResponse *, const char*);
SOAP_FMAC3 struct ns1__addResponse * SOAP_FMAC4 soap_in_ns1__addResponse(struct soap*, const char*, struct ns1__addResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__addResponse(struct soap*, const struct ns1__addResponse *, const char*, const char*);

#ifndef soap_write_ns1__addResponse
#define soap_write_ns1__addResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__addResponse(soap, data),0) || soap_put_ns1__addResponse(soap, data, "ns1:addResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__addResponse * SOAP_FMAC4 soap_get_ns1__addResponse(struct soap*, struct ns1__addResponse *, const char*, const char*);

#ifndef soap_read_ns1__addResponse
#define soap_read_ns1__addResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__addResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__addResponse * SOAP_FMAC2 soap_instantiate_ns1__addResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__addResponse * soap_new_ns1__addResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__addResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__addResponse * soap_new_req_ns1__addResponse(struct soap *soap, LONG64 _return_) { struct ns1__addResponse *_p = soap_instantiate_ns1__addResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__addResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ns1__addResponse * soap_new_set_ns1__addResponse(struct soap *soap, LONG64 _return_) { struct ns1__addResponse *_p = soap_instantiate_ns1__addResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__addResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ns1__addResponse(struct soap *soap, struct ns1__addResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__addResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dic
#define SOAP_TYPE_ns1__dic (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dic(struct soap*, struct ns1__dic *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dic(struct soap*, const struct ns1__dic *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dic(struct soap*, const char*, int, const struct ns1__dic *, const char*);
SOAP_FMAC3 struct ns1__dic * SOAP_FMAC4 soap_in_ns1__dic(struct soap*, const char*, struct ns1__dic *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dic(struct soap*, const struct ns1__dic *, const char*, const char*);

#ifndef soap_write_ns1__dic
#define soap_write_ns1__dic(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__dic(soap, data),0) || soap_put_ns1__dic(soap, data, "ns1:dic", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__dic * SOAP_FMAC4 soap_get_ns1__dic(struct soap*, struct ns1__dic *, const char*, const char*);

#ifndef soap_read_ns1__dic
#define soap_read_ns1__dic(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dic(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__dic * SOAP_FMAC2 soap_instantiate_ns1__dic(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dic * soap_new_ns1__dic(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dic(soap, n, NULL, NULL, NULL); }

inline struct ns1__dic * soap_new_req_ns1__dic(struct soap *soap, int _arg0, int _arg1) { struct ns1__dic *_p = soap_instantiate_ns1__dic(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dic(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline struct ns1__dic * soap_new_set_ns1__dic(struct soap *soap, int _arg0, int _arg1) { struct ns1__dic *_p = soap_instantiate_ns1__dic(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dic(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline void soap_delete_ns1__dic(struct soap *soap, struct ns1__dic *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dic(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dicResponse
#define SOAP_TYPE_ns1__dicResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dicResponse(struct soap*, struct ns1__dicResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dicResponse(struct soap*, const struct ns1__dicResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dicResponse(struct soap*, const char*, int, const struct ns1__dicResponse *, const char*);
SOAP_FMAC3 struct ns1__dicResponse * SOAP_FMAC4 soap_in_ns1__dicResponse(struct soap*, const char*, struct ns1__dicResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dicResponse(struct soap*, const struct ns1__dicResponse *, const char*, const char*);

#ifndef soap_write_ns1__dicResponse
#define soap_write_ns1__dicResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__dicResponse(soap, data),0) || soap_put_ns1__dicResponse(soap, data, "ns1:dicResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__dicResponse * SOAP_FMAC4 soap_get_ns1__dicResponse(struct soap*, struct ns1__dicResponse *, const char*, const char*);

#ifndef soap_read_ns1__dicResponse
#define soap_read_ns1__dicResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dicResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__dicResponse * SOAP_FMAC2 soap_instantiate_ns1__dicResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dicResponse * soap_new_ns1__dicResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dicResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__dicResponse * soap_new_req_ns1__dicResponse(struct soap *soap, LONG64 _return_) { struct ns1__dicResponse *_p = soap_instantiate_ns1__dicResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dicResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ns1__dicResponse * soap_new_set_ns1__dicResponse(struct soap *soap, LONG64 _return_) { struct ns1__dicResponse *_p = soap_instantiate_ns1__dicResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dicResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ns1__dicResponse(struct soap *soap, struct ns1__dicResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dicResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__mul
#define SOAP_TYPE_ns1__mul (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__mul(struct soap*, struct ns1__mul *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__mul(struct soap*, const struct ns1__mul *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__mul(struct soap*, const char*, int, const struct ns1__mul *, const char*);
SOAP_FMAC3 struct ns1__mul * SOAP_FMAC4 soap_in_ns1__mul(struct soap*, const char*, struct ns1__mul *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__mul(struct soap*, const struct ns1__mul *, const char*, const char*);

#ifndef soap_write_ns1__mul
#define soap_write_ns1__mul(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__mul(soap, data),0) || soap_put_ns1__mul(soap, data, "ns1:mul", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__mul * SOAP_FMAC4 soap_get_ns1__mul(struct soap*, struct ns1__mul *, const char*, const char*);

#ifndef soap_read_ns1__mul
#define soap_read_ns1__mul(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__mul(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__mul * SOAP_FMAC2 soap_instantiate_ns1__mul(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__mul * soap_new_ns1__mul(struct soap *soap, int n = -1) { return soap_instantiate_ns1__mul(soap, n, NULL, NULL, NULL); }

inline struct ns1__mul * soap_new_req_ns1__mul(struct soap *soap, int _arg0, int _arg1) { struct ns1__mul *_p = soap_instantiate_ns1__mul(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__mul(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline struct ns1__mul * soap_new_set_ns1__mul(struct soap *soap, int _arg0, int _arg1) { struct ns1__mul *_p = soap_instantiate_ns1__mul(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__mul(soap, _p); _p->_arg0 = _arg0; _p->_arg1 = _arg1; } return _p; }

inline void soap_delete_ns1__mul(struct soap *soap, struct ns1__mul *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__mul(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__mulResponse
#define SOAP_TYPE_ns1__mulResponse (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__mulResponse(struct soap*, struct ns1__mulResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__mulResponse(struct soap*, const struct ns1__mulResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__mulResponse(struct soap*, const char*, int, const struct ns1__mulResponse *, const char*);
SOAP_FMAC3 struct ns1__mulResponse * SOAP_FMAC4 soap_in_ns1__mulResponse(struct soap*, const char*, struct ns1__mulResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__mulResponse(struct soap*, const struct ns1__mulResponse *, const char*, const char*);

#ifndef soap_write_ns1__mulResponse
#define soap_write_ns1__mulResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__mulResponse(soap, data),0) || soap_put_ns1__mulResponse(soap, data, "ns1:mulResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__mulResponse * SOAP_FMAC4 soap_get_ns1__mulResponse(struct soap*, struct ns1__mulResponse *, const char*, const char*);

#ifndef soap_read_ns1__mulResponse
#define soap_read_ns1__mulResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__mulResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns1__mulResponse * SOAP_FMAC2 soap_instantiate_ns1__mulResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__mulResponse * soap_new_ns1__mulResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__mulResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__mulResponse * soap_new_req_ns1__mulResponse(struct soap *soap, LONG64 _return_) { struct ns1__mulResponse *_p = soap_instantiate_ns1__mulResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__mulResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ns1__mulResponse * soap_new_set_ns1__mulResponse(struct soap *soap, LONG64 _return_) { struct ns1__mulResponse *_p = soap_instantiate_ns1__mulResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__mulResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ns1__mulResponse(struct soap *soap, struct ns1__mulResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__mulResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
