# Makefile f. dbnm

all:
	gcc -Wall dbnm.c -o dbnm.exe
	
run:
	dbnm.exe
	
ansi:
	gcc -ansi dbnm.c -o dbnm.exe
	
pedantic:
	gcc -pedantic dbnm.c -o dbnm.exe
	
optimize:
	gcc -Wall dbnm.c -o dbnm.exe -O
	
optimize2:
	gcc -Wall dbnm.c -o dbnm.exe -O2