# Threads in Java: Basic

00:
	javac OS00_PunktStrich.java
	java  OS00_PunktStrich
01:
	javac OS01_LostUpdate.java
	java  OS01_LostUpdate
02:
	javac OS02_LostUpdate_Synchronized.java
	java  OS02_LostUpdate_Synchronized

# Vortrag 01: Wie funktioniert ein Semaphore? (wait/notify) (Bahngleis)	
03:
	javac OS03_FIFO.java
	java  OS03_FIFO

# Vortrag 02: FIFOs und Producer/Consumer Threads
#				1. Ereignis-Synchronisation u. FIFO
#				2. Sperr-Synchronisation u. FIFO

04:
	javac OS04_FIFO_Synchronized.java
	java  OS04_FIFO_Synchronized

05:
# OS/02-THREADS/02-ueben/ue-java/BSXXLOSTUPDATE-Bank-UE.zip

06:
# OS/02-THREADS/02-ueben/ue-java/BS08Eratosthenes_UE.zip

07:
# eclipse-Projekt mit Swing
# OS/02-THREADS/02-ueben/ue-java/BSXXSwingProducerConsumer-SliderUE.zip
# 

08:
#MAB BS08Sort

09:
#ABSCHLUSS-PROJEKT: OS/02-THREADS/02-ueben/ue-java/AB-02-BSXXConsumerProducer-JFreeChart-Queue-Socket.txt

clean:
	rm *class
