# floyd-warshall: all pair shortest path
# --------------------------------------
net:
	g++ main.cpp net.cpp -o main.exe
run:
	./main.exe
clean:
	rm *.exe


# matrix als template Klasse
# --------------------------
matrix:
	g++ test-matrix.cpp -o test-matrix.exe
